package com.example.recipeapp

const val ARG_CATEGORY_ID = "ARG_CATEGORY_ID"
const val ARG_CATEGORY_NAME = "ARG_CATEGORY_NAME"
const val ARG_CATEGORY_IMAGE_URL = "ARG_CATEGORY_IMAGE_URL"
const val ARG_RECIPE = "ARG_RECIPE"